const mongoose = require('mongoose');
const dotenv = require('dotenv');
dotenv.config();

const connectDB = require('../config/db');
const User = require('../models/User');
const Category = require('../models/Category');
const Product = require('../models/Product');
const Review = require('../models/Review');
const Order = require('../models/Order');

const sampleCategories = [
  { name: 'Electronics', slug: 'electronics', image: 'https://images.unsplash.com/photo-1498049860654-af1a5c570f1a?w=800', description: 'Smartphones, noise-canceling headphones, laptops & smart tech.' },
  { name: 'Fashion', slug: 'fashion', image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=800', description: 'Designer apparel, outerwear, sweaters, and street fashion.' },
  { name: 'Shoes', slug: 'shoes', image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800', description: 'Performance sneakers, boots, loafers, and athletic footwear.' },
  { name: 'Beauty', slug: 'beauty', image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800', description: 'Skincare, hydration serums, cosmetics, and self-care.' },
  { name: 'Home & Kitchen', slug: 'home-kitchen', image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800', description: 'Espresso machines, vacuums, cookware, and smart home tech.' },
  { name: 'Furniture', slug: 'furniture', image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800', description: 'Ergonomic office chairs, walnut desks, sofas & ambient lamps.' },
  { name: 'Sports', slug: 'sports', image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800', description: 'Yoga mats, dumbbells, running gear, and fitness smartwatches.' },
  { name: 'Books', slug: 'books', image: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800', description: 'Bestselling literature, tech architecture, self-improvement & journals.' },
  { name: 'Grocery', slug: 'grocery', image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800', description: 'Single-origin coffee, extra virgin olive oil, matcha & organic honey.' },
  { name: 'Accessories', slug: 'accessories', image: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800', description: 'Polarized sunglasses, full-grain leather wallets, and travel gear.' }
];

// Generate 100 realistic sample products across 10 categories
const sampleProducts = [
  // ELECTRONICS (10)
  {
    title: 'Sony WH-1000XM5 Wireless Headphones',
    slug: 'sony-wh1000xm5-wireless-headphones',
    price: 399,
    discountPrice: 349,
    stock: 25,
    category: 'electronics',
    categoryName: 'Electronics',
    brand: 'Sony',
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800'],
    description: 'Industry-leading noise canceling headphones with 8 microphones for crystal clear audio.',
    shortDescription: '30-hr battery life, touch controls.',
    specifications: [{ key: 'Battery', value: '30 Hours' }, { key: 'Bluetooth', value: '5.2' }],
    tags: ['audio', 'headphones', 'sony'],
    rating: 4.9,
    numReviews: 128,
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    isFlashSale: true,
    isTrending: true,
    isTopRated: true,
    salesCount: 420
  },
  {
    title: 'Apple MacBook Air 15-Inch M3',
    slug: 'apple-macbook-air-15-m3',
    price: 1299,
    discountPrice: 1199,
    stock: 14,
    category: 'electronics',
    categoryName: 'Electronics',
    brand: 'Apple',
    images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800'],
    description: 'Supercharged by M3 chip with Liquid Retina display in a ultra-light aluminum enclosure.',
    shortDescription: '15.3" Liquid Retina, 16GB RAM, 512GB SSD.',
    specifications: [{ key: 'Chip', value: 'Apple M3' }],
    tags: ['laptop', 'apple', 'macbook'],
    rating: 5.0,
    numReviews: 95,
    isFeatured: true,
    isBestSeller: true,
    isTopRated: true,
    salesCount: 310
  },
  {
    title: 'Samsung Galaxy Watch 6 Classic LTE',
    slug: 'samsung-galaxy-watch-6-classic',
    price: 399,
    discountPrice: 320,
    stock: 18,
    category: 'electronics',
    categoryName: 'Electronics',
    brand: 'Samsung',
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800'],
    description: 'Rotating bezel with advanced sleep tracking and sapphire glass display.',
    shortDescription: '47mm Stainless Steel case.',
    specifications: [{ key: 'Display', value: '1.5" Super AMOLED' }],
    tags: ['smartwatch', 'samsung'],
    rating: 4.7,
    numReviews: 64,
    isFlashSale: true,
    isTrending: true,
    salesCount: 180
  },
  {
    title: 'Bose Smart Soundbar 900 Dolby Atmos',
    slug: 'bose-smart-soundbar-900',
    price: 899,
    discountPrice: 799,
    stock: 10,
    category: 'electronics',
    categoryName: 'Electronics',
    brand: 'Bose',
    images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800'],
    description: 'Spatial audio soundbar with dipole speakers for immersive 3D surround sound.',
    shortDescription: 'Dolby Atmos, Voice Assistant built-in.',
    specifications: [{ key: 'Audio', value: 'Dolby Atmos' }],
    tags: ['audio', 'bose', 'soundbar'],
    rating: 4.8,
    numReviews: 42,
    isTrending: true,
    salesCount: 120
  },
  {
    title: 'Dell XPS 13 Ultrabook Touchscreen',
    slug: 'dell-xps-13-ultrabook',
    price: 1150,
    discountPrice: 999,
    stock: 12,
    category: 'electronics',
    categoryName: 'Electronics',
    brand: 'Dell',
    images: ['https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800'],
    description: 'InfinityEdge 4K display powered by 13th Gen Intel Core i7 with 16GB LPDDR5 RAM.',
    shortDescription: 'Intel i7, 16GB RAM, 1TB SSD.',
    specifications: [{ key: 'CPU', value: 'Intel Core i7' }],
    tags: ['laptop', 'dell'],
    rating: 4.7,
    numReviews: 38,
    salesCount: 140
  },
  {
    title: 'Apple iPad Pro 12.9-Inch M2',
    slug: 'apple-ipad-pro-12-9-m2',
    price: 1099,
    discountPrice: 999,
    stock: 16,
    category: 'electronics',
    categoryName: 'Electronics',
    brand: 'Apple',
    images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800'],
    description: 'Liquid Retina XDR display with ProMotion 120Hz and M2 processor power.',
    shortDescription: '128GB Wi-Fi Space Gray.',
    specifications: [{ key: 'Screen', value: '12.9" Mini-LED' }],
    tags: ['tablet', 'apple', 'ipad'],
    rating: 4.9,
    numReviews: 88,
    isFeatured: true,
    salesCount: 260
  },
  {
    title: 'Logitech MX Master 3S Wireless Mouse',
    slug: 'logitech-mx-master-3s-mouse',
    price: 99,
    discountPrice: 84,
    stock: 35,
    category: 'electronics',
    categoryName: 'Electronics',
    brand: 'Logitech',
    images: ['https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800'],
    description: 'Quiet Click technology with 8K DPI track-on-glass sensor and MagSpeed wheel.',
    shortDescription: '8000 DPI, Quiet clicks.',
    specifications: [{ key: 'DPI', value: '8000' }],
    tags: ['mouse', 'logitech'],
    rating: 4.9,
    numReviews: 145,
    isBestSeller: true,
    salesCount: 510
  },
  {
    title: 'GoPro HERO12 Black Action Camera',
    slug: 'gopro-hero12-black-action-camera',
    price: 399,
    discountPrice: 349,
    stock: 20,
    category: 'electronics',
    categoryName: 'Electronics',
    brand: 'GoPro',
    images: ['https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=800'],
    description: '5.3K video resolution with HDR, HyperSmooth 6.0 stabilization.',
    shortDescription: '5.3K 60fps video, 27MP photos.',
    specifications: [{ key: 'Video', value: '5.3K 60fps' }],
    tags: ['camera', 'gopro'],
    rating: 4.8,
    numReviews: 52,
    salesCount: 190
  },
  {
    title: 'Asus ROG Swift 27" 240Hz Gaming Monitor',
    slug: 'asus-rog-swift-27-gaming-monitor',
    price: 699,
    discountPrice: 599,
    stock: 10,
    category: 'electronics',
    categoryName: 'Electronics',
    brand: 'Asus',
    images: ['https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800'],
    description: 'QHD 1440p Fast IPS gaming monitor with 240Hz refresh rate.',
    shortDescription: '2560x1440 QHD, 1ms response time.',
    specifications: [{ key: 'Refresh Rate', value: '240Hz' }],
    tags: ['gaming', 'monitor', 'asus'],
    rating: 4.8,
    numReviews: 40,
    salesCount: 110
  },
  {
    title: 'Anker Magnetic 10000mAh Power Bank',
    slug: 'anker-magnetic-10000mAh-power-bank',
    price: 49,
    discountPrice: 39,
    stock: 50,
    category: 'electronics',
    categoryName: 'Electronics',
    brand: 'Anker',
    images: ['https://images.unsplash.com/photo-1609592424083-d9d3005f5647?w=800'],
    description: 'MagSafe compatible portable charger with kickstand and 20W output.',
    shortDescription: '10000mAh capacity.',
    specifications: [{ key: 'Capacity', value: '10000mAh' }],
    tags: ['charger', 'anker'],
    rating: 4.7,
    numReviews: 95,
    isFlashSale: true,
    salesCount: 320
  },

  // FASHION (10)
  {
    title: 'Minimalist Wool Blend Trench Coat',
    slug: 'minimalist-wool-blend-trench-coat',
    price: 280,
    discountPrice: 220,
    stock: 22,
    category: 'fashion',
    categoryName: 'Fashion',
    brand: 'Nexora Fashion',
    images: ['https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800'],
    description: 'Tailored trench coat crafted from premium Australian merino wool blend.',
    shortDescription: '80% Merino Wool blend.',
    specifications: [{ key: 'Material', value: '80% Wool, 20% Cashmere' }],
    tags: ['coat', 'winter', 'fashion'],
    rating: 4.8,
    numReviews: 38,
    isFeatured: true,
    isNewArrival: true,
    isTopRated: true,
    salesCount: 240
  },
  {
    title: 'Pure Cashmere Oversized Sweater',
    slug: 'pure-cashmere-oversized-sweater',
    price: 195,
    discountPrice: 155,
    stock: 30,
    category: 'fashion',
    categoryName: 'Fashion',
    brand: 'Nexora Fashion',
    images: ['https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800'],
    description: 'Ultra-soft Mongolian cashmere knit with ribbed turtleneck collar.',
    shortDescription: '100% Mongolian Cashmere.',
    specifications: [{ key: 'Material', value: '100% Cashmere' }],
    tags: ['sweater', 'cashmere'],
    rating: 4.9,
    numReviews: 76,
    isBestSeller: true,
    isTrending: true,
    salesCount: 390
  },
  {
    title: 'Vintage Wash Denim Trucker Jacket',
    slug: 'vintage-wash-denim-jacket',
    price: 120,
    discountPrice: 95,
    stock: 35,
    category: 'fashion',
    categoryName: 'Fashion',
    brand: 'Levi\'s',
    images: ['https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800'],
    description: 'Classic trucker silhouette in 100% heavy cotton denim with vintage distressing.',
    shortDescription: '14oz Cotton Denim.',
    specifications: [{ key: 'Fabric', value: '100% Cotton Denim' }],
    tags: ['denim', 'levis'],
    rating: 4.7,
    numReviews: 52,
    salesCount: 210
  },
  {
    title: 'Tailored Slim Fit Cotton Chinos',
    slug: 'tailored-slim-fit-chino-pants',
    price: 75,
    discountPrice: 59,
    stock: 40,
    category: 'fashion',
    categoryName: 'Fashion',
    brand: 'Zara',
    images: ['https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800'],
    description: 'Stretch-cotton twill chinos with flat-front tailoring.',
    shortDescription: '98% Cotton, 2% Elastane.',
    specifications: [{ key: 'Fit', value: 'Slim Fit' }],
    tags: ['chinos', 'pants'],
    rating: 4.6,
    numReviews: 60,
    salesCount: 280
  },
  {
    title: '100% Mulberry Silk Button-Down Shirt',
    slug: 'mulberry-silk-button-down-shirt',
    price: 145,
    discountPrice: 115,
    stock: 20,
    category: 'fashion',
    categoryName: 'Fashion',
    brand: 'Nexora Fashion',
    images: ['https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=800'],
    description: '19mm momme Mulberry silk shirt with mother-of-pearl buttons.',
    shortDescription: '100% Mulberry Silk.',
    specifications: [{ key: 'Material', value: '100% Silk' }],
    tags: ['silk', 'shirt'],
    rating: 4.9,
    numReviews: 44,
    isFeatured: true,
    salesCount: 175
  },
  {
    title: 'Quilted Lightweight Puffer Vest',
    slug: 'quilted-lightweight-puffer-vest',
    price: 110,
    discountPrice: 85,
    stock: 25,
    category: 'fashion',
    categoryName: 'Fashion',
    brand: 'Ralph Lauren',
    images: ['https://images.unsplash.com/photo-1544441893-675973e31985?w=800'],
    description: 'Water-resistant ripstop shell insulated with recycled fill.',
    shortDescription: 'Packable insulated vest.',
    specifications: [{ key: 'Fill', value: 'Recycled Fill' }],
    tags: ['vest', 'ralphlauren'],
    rating: 4.8,
    numReviews: 32,
    salesCount: 150
  },
  {
    title: 'Pleated Satin A-Line Midi Skirt',
    slug: 'pleated-a-line-midi-skirt',
    price: 89,
    discountPrice: 69,
    stock: 28,
    category: 'fashion',
    categoryName: 'Fashion',
    brand: 'Zara',
    images: ['https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=800'],
    description: 'Knife-pleated midi skirt in champagne satin fabric.',
    shortDescription: 'High elastic waistband.',
    specifications: [{ key: 'Length', value: 'Midi' }],
    tags: ['skirt', 'zara'],
    rating: 4.7,
    numReviews: 29,
    salesCount: 130
  },
  {
    title: 'Classic Heavyweight Hoodie 450gsm',
    slug: 'classic-heavyweight-hoodie-450gsm',
    price: 95,
    discountPrice: 75,
    stock: 45,
    category: 'fashion',
    categoryName: 'Fashion',
    brand: 'Nexora Fashion',
    images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800'],
    description: '450gsm organic French terry cotton hoodie with double-lined hood.',
    shortDescription: '450gsm Organic Cotton.',
    specifications: [{ key: 'Weight', value: '450gsm' }],
    tags: ['hoodie', 'streetwear'],
    rating: 4.9,
    numReviews: 110,
    isBestSeller: true,
    salesCount: 460
  },
  {
    title: 'Relaxed Fit Linen Blend Blazer',
    slug: 'relaxed-fit-linen-blend-blazer',
    price: 165,
    discountPrice: 129,
    stock: 18,
    category: 'fashion',
    categoryName: 'Fashion',
    brand: 'Zara',
    images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800'],
    description: 'Linen-cotton blend single-breasted blazer for summer tailoring.',
    shortDescription: '55% Linen, 45% Cotton.',
    specifications: [{ key: 'Material', value: 'Linen Blend' }],
    tags: ['blazer', 'zara'],
    rating: 4.8,
    numReviews: 36,
    salesCount: 140
  },
  {
    title: 'Organic Cotton Crewneck T-Shirt 3-Pack',
    slug: 'organic-cotton-tshirt-3pack',
    price: 60,
    discountPrice: 45,
    stock: 60,
    category: 'fashion',
    categoryName: 'Fashion',
    brand: 'Nexora Fashion',
    images: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800'],
    description: '3-pack t-shirts crafted from GOTS certified organic combed cotton.',
    shortDescription: 'White, Gray & Black 3-Pack.',
    specifications: [{ key: 'Pack', value: '3 Shirts' }],
    tags: ['tshirt', 'basics'],
    rating: 4.8,
    numReviews: 180,
    isFlashSale: true,
    salesCount: 620
  },

  // SHOES (10)
  {
    title: 'Nike Air Max 270 React Sneakers',
    slug: 'nike-air-max-270-react',
    price: 160,
    discountPrice: 135,
    stock: 40,
    category: 'shoes',
    categoryName: 'Shoes',
    brand: 'Nike',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800'],
    description: 'Max Air 270 unit delivers all-day comfort with React foam technology.',
    shortDescription: 'Breathable mesh upper.',
    specifications: [{ key: 'Upper', value: 'Mesh' }],
    tags: ['nike', 'sneakers'],
    rating: 4.9,
    numReviews: 210,
    isFeatured: true,
    isBestSeller: true,
    isTrending: true,
    salesCount: 850
  },
  {
    title: 'Handcrafted Italian Leather Chelsea Boots',
    slug: 'italian-leather-chelsea-boots',
    price: 260,
    discountPrice: 210,
    stock: 15,
    category: 'shoes',
    categoryName: 'Shoes',
    brand: 'Nexora Footwear',
    images: ['https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=800'],
    description: 'Hand-finished Tuscan full-grain leather boots with Goodyear welted rubber sole.',
    shortDescription: 'Goodyear welted Tuscan calfskin.',
    specifications: [{ key: 'Upper', value: 'Calfskin' }],
    tags: ['boots', 'leather'],
    rating: 4.9,
    numReviews: 48,
    isTopRated: true,
    salesCount: 160
  },
  {
    title: 'Adidas Ultraboost Light Running Shoes',
    slug: 'adidas-ultraboost-light',
    price: 190,
    discountPrice: 159,
    stock: 28,
    category: 'shoes',
    categoryName: 'Shoes',
    brand: 'Adidas',
    images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800'],
    description: 'Light BOOST material for maximum energy return on long runs.',
    shortDescription: 'Primeknit+ upper.',
    specifications: [{ key: 'Cushioning', value: 'Light BOOST' }],
    tags: ['adidas', 'running'],
    rating: 4.8,
    numReviews: 115,
    isFlashSale: true,
    salesCount: 490
  },
  {
    title: 'Puma RS-X Retro Sneakers',
    slug: 'puma-rsx-reinvention-sneakers',
    price: 110,
    discountPrice: 89,
    stock: 32,
    category: 'shoes',
    categoryName: 'Shoes',
    brand: 'Puma',
    images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800'],
    description: 'Bulky retro runner silhouette with Running System technology.',
    shortDescription: 'Mesh & leather upper.',
    specifications: [{ key: 'Technology', value: 'RS System' }],
    tags: ['puma', 'sneakers'],
    rating: 4.7,
    numReviews: 75,
    salesCount: 310
  },
  {
    title: 'New Balance 574 Core Classic',
    slug: 'new-balance-574-classic',
    price: 90,
    discountPrice: 75,
    stock: 45,
    category: 'shoes',
    categoryName: 'Shoes',
    brand: 'New Balance',
    images: ['https://images.unsplash.com/photo-1539185441755-769473a23570?w=800'],
    description: 'Suede and mesh upper with ENCAP midsole technology.',
    shortDescription: 'ENCAP midsole cushioning.',
    specifications: [{ key: 'Upper', value: 'Suede / Mesh' }],
    tags: ['newbalance', 'sneakers'],
    rating: 4.8,
    numReviews: 140,
    isBestSeller: true,
    salesCount: 580
  },
  {
    title: 'Timberland 6-Inch Premium Boots',
    slug: 'timberland-6inch-premium-boots',
    price: 198,
    discountPrice: 169,
    stock: 22,
    category: 'shoes',
    categoryName: 'Shoes',
    brand: 'Timberland',
    images: ['https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=800'],
    description: 'Seam-sealed waterproof construction with 400g PrimaLoft insulation.',
    shortDescription: 'Premium waterproof nubuck.',
    specifications: [{ key: 'Insulation', value: '400g PrimaLoft' }],
    tags: ['timberland', 'boots'],
    rating: 4.9,
    numReviews: 190,
    isFeatured: true,
    salesCount: 420
  },
  {
    title: 'Classic Suede Penny Loafers',
    slug: 'classic-suede-penny-loafers',
    price: 140,
    discountPrice: 110,
    stock: 18,
    category: 'shoes',
    categoryName: 'Shoes',
    brand: 'Nexora Footwear',
    images: ['https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=800'],
    description: 'Water-repellent suede leather loafers with leather lining.',
    shortDescription: 'Italian calf suede upper.',
    specifications: [{ key: 'Lining', value: 'Leather' }],
    tags: ['loafers', 'suede'],
    rating: 4.8,
    numReviews: 34,
    salesCount: 130
  },
  {
    title: 'Vans Old Skool Core Skate Shoes',
    slug: 'vans-old-skool-skate-shoes',
    price: 70,
    discountPrice: 58,
    stock: 50,
    category: 'shoes',
    categoryName: 'Shoes',
    brand: 'Vans',
    images: ['https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800'],
    description: 'Low-top side-stripe skate shoe with waffle rubber outsole.',
    shortDescription: 'Canvas & suede upper.',
    specifications: [{ key: 'Outsole', value: 'Waffle Rubber' }],
    tags: ['vans', 'skate'],
    rating: 4.8,
    numReviews: 240,
    isTrending: true,
    salesCount: 790
  },
  {
    title: 'Birkenstock Arizona Soft Footbed Sandals',
    slug: 'birkenstock-arizona-sandals',
    price: 135,
    discountPrice: 115,
    stock: 30,
    category: 'shoes',
    categoryName: 'Shoes',
    brand: 'Birkenstock',
    images: ['https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=800'],
    description: 'Cork-latex footbed lined with soft suede leather.',
    shortDescription: 'Oiled leather two-strap sandal.',
    specifications: [{ key: 'Footbed', value: 'Cork-Latex' }],
    tags: ['sandals', 'birkenstock'],
    rating: 4.9,
    numReviews: 165,
    salesCount: 450
  },
  {
    title: 'Converse Chuck Taylor All Star High-Top',
    slug: 'converse-chuck-taylor-high-top',
    price: 65,
    discountPrice: 52,
    stock: 55,
    category: 'shoes',
    categoryName: 'Shoes',
    brand: 'Converse',
    images: ['https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=800'],
    description: 'Canvas upper with star ankle patch and vulcanized rubber sole.',
    shortDescription: 'High-top canvas sneaker.',
    specifications: [{ key: 'Upper', value: 'Canvas' }],
    tags: ['converse', 'sneakers'],
    rating: 4.8,
    numReviews: 310,
    salesCount: 940
  },

  // BEAUTY (10)
  {
    title: 'Estée Lauder Advanced Night Repair Serum 50ml',
    slug: 'advanced-night-repair-serum',
    price: 115,
    discountPrice: 95,
    stock: 45,
    category: 'beauty',
    categoryName: 'Beauty',
    brand: 'Estée Lauder',
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800'],
    description: 'Chronolux technology reduces visible signs of skin aging.',
    shortDescription: 'Anti-aging facial serum 50ml.',
    specifications: [{ key: 'Volume', value: '50ml' }],
    tags: ['skincare', 'serum'],
    rating: 4.9,
    numReviews: 340,
    isFeatured: true,
    isBestSeller: true,
    isTopRated: true,
    salesCount: 920
  },
  {
    title: 'Rose Gold Glow Highlighter Palette',
    slug: 'rose-gold-glow-highlighter-palette',
    price: 48,
    discountPrice: 38,
    stock: 50,
    category: 'beauty',
    categoryName: 'Beauty',
    brand: 'Nexora Beauty',
    images: ['https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=800'],
    description: 'Bronzer, blush, and highlighter quad infused with jojoba oil.',
    shortDescription: 'Cruelty-free 4-shade quad.',
    specifications: [{ key: 'Finish', value: 'Radiant' }],
    tags: ['makeup', 'palette'],
    rating: 4.7,
    numReviews: 62,
    isTrending: true,
    salesCount: 310
  },
  {
    title: 'Dior Sauvage Eau De Parfum 100ml',
    slug: 'dior-sauvage-edp-100ml',
    price: 145,
    discountPrice: 125,
    stock: 25,
    category: 'beauty',
    categoryName: 'Beauty',
    brand: 'Dior',
    images: ['https://images.unsplash.com/photo-1541643600914-78b084683601?w=800'],
    description: 'Calabrian bergamot blended with Papua New Guinean vanilla.',
    shortDescription: 'Woody & spicy fragrance 100ml.',
    specifications: [{ key: 'Volume', value: '100ml' }],
    tags: ['perfume', 'dior'],
    rating: 4.9,
    numReviews: 280,
    isFeatured: true,
    salesCount: 740
  },
  {
    title: 'Hyaluronic Acid 2% + B5 Hydration Serum',
    slug: 'hyaluronic-acid-hydration-serum',
    price: 25,
    discountPrice: 19,
    stock: 75,
    category: 'beauty',
    categoryName: 'Beauty',
    brand: 'Sephora',
    images: ['https://images.unsplash.com/photo-1608248597263-0057e57b4524?w=800'],
    description: 'Multi-depth hydration formula with hyaluronic acid.',
    shortDescription: '30ml oil-free serum.',
    specifications: [{ key: 'Skin Type', value: 'All Types' }],
    tags: ['skincare', 'sephora'],
    rating: 4.8,
    numReviews: 410,
    isFlashSale: true,
    salesCount: 1200
  },
  {
    title: 'Fenty Beauty Gloss Bomb Universal Lip Luminizer',
    slug: 'fenty-gloss-bomb-lip-luminizer',
    price: 22,
    discountPrice: 18,
    stock: 60,
    category: 'beauty',
    categoryName: 'Beauty',
    brand: 'Fenty',
    images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800'],
    description: 'Shea butter lip gloss that delivers high shine.',
    shortDescription: 'Non-sticky high-shine gloss.',
    specifications: [{ key: 'Key Ingredient', value: 'Shea Butter' }],
    tags: ['makeup', 'fenty'],
    rating: 4.9,
    numReviews: 320,
    isBestSeller: true,
    salesCount: 890
  },
  {
    title: 'Botanical Argan Oil Hair Mask 250ml',
    slug: 'botanical-argan-oil-hair-mask',
    price: 38,
    discountPrice: 29,
    stock: 40,
    category: 'beauty',
    categoryName: 'Beauty',
    brand: 'Nexora Beauty',
    images: ['https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=800'],
    description: 'Deep conditioning treatment enriched with Moroccan argan oil.',
    shortDescription: 'Restorative mask 250ml.',
    specifications: [{ key: 'Volume', value: '250ml' }],
    tags: ['haircare', 'argan'],
    rating: 4.8,
    numReviews: 85,
    salesCount: 340
  },
  {
    title: 'Vitamin C 20% Radiance Facial Cream',
    slug: 'vitamin-c-radiance-facial-cream',
    price: 55,
    discountPrice: 42,
    stock: 35,
    category: 'beauty',
    categoryName: 'Beauty',
    brand: 'L\'Oréal',
    images: ['https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800'],
    description: 'L-ascorbic acid formula for brightening uneven skin tone.',
    shortDescription: 'Antioxidant moisturizer 50ml.',
    specifications: [{ key: 'Vitamin C', value: '20%' }],
    tags: ['skincare', 'loreal'],
    rating: 4.7,
    numReviews: 95,
    salesCount: 290
  },
  {
    title: 'Organic Rosewater Hydrating Face Mist',
    slug: 'organic-rosewater-face-mist',
    price: 24,
    discountPrice: 18,
    stock: 50,
    category: 'beauty',
    categoryName: 'Beauty',
    brand: 'Nexora Beauty',
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800'],
    description: '100% pure Damask rose petal water spray.',
    shortDescription: '100ml facial mist.',
    specifications: [{ key: 'Origin', value: 'Bulgarian Rose' }],
    tags: ['facemist', 'organic'],
    rating: 4.8,
    numReviews: 120,
    salesCount: 410
  },
  {
    title: 'Niacinamide 10% + Zinc 1% Pore Refining Serum',
    slug: 'niacinamide-zinc-pore-serum',
    price: 20,
    discountPrice: 15,
    stock: 65,
    category: 'beauty',
    categoryName: 'Beauty',
    brand: 'Sephora',
    images: ['https://images.unsplash.com/photo-1608248597263-0057e57b4524?w=800'],
    description: 'High-strength vitamin & mineral blemish serum.',
    shortDescription: '30ml pore-refining serum.',
    specifications: [{ key: 'Niacinamide', value: '10%' }],
    tags: ['niacinamide', 'skincare'],
    rating: 4.8,
    numReviews: 290,
    salesCount: 810
  },
  {
    title: 'Velvet Matte Longwear Liquid Lipstick',
    slug: 'velvet-matte-liquid-lipstick',
    price: 26,
    discountPrice: 20,
    stock: 45,
    category: 'beauty',
    categoryName: 'Beauty',
    brand: 'Fenty',
    images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800'],
    description: 'Transfer-resistant weightless liquid lip color.',
    shortDescription: '12-hour matte lip color.',
    specifications: [{ key: 'Finish', value: 'Velvet Matte' }],
    tags: ['lipstick', 'makeup'],
    rating: 4.9,
    numReviews: 140,
    salesCount: 520
  },

  // HOME & KITCHEN (10)
  {
    title: 'DeLonghi Specialista Espresso Machine',
    slug: 'delonghi-specialista-espresso-machine',
    price: 899,
    discountPrice: 749,
    stock: 12,
    category: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    brand: 'DeLonghi',
    images: ['https://images.unsplash.com/photo-1517668808822-9ebd02f2a888?w=800'],
    description: 'Sensor grinding technology with smart tamping station and 19-bar pump.',
    shortDescription: '19-bar espresso maker.',
    specifications: [{ key: 'Pressure', value: '19 Bar' }],
    tags: ['espresso', 'delonghi'],
    rating: 4.9,
    numReviews: 88,
    isFeatured: true,
    isBestSeller: true,
    isTopRated: true,
    salesCount: 290
  },
  {
    title: 'Dyson V15 Detect Cordless Vacuum',
    slug: 'dyson-v15-detect-cordless-vacuum',
    price: 749,
    discountPrice: 649,
    stock: 16,
    category: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    brand: 'Dyson',
    images: ['https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800'],
    description: 'Laser reveals invisible dust with piezo sensor power optimization.',
    shortDescription: '60 min run time.',
    specifications: [{ key: 'Run Time', value: '60 Mins' }],
    tags: ['dyson', 'vacuum'],
    rating: 4.9,
    numReviews: 145,
    isFlashSale: true,
    isTrending: true,
    salesCount: 510
  },
  {
    title: 'KitchenAid Artisan 5-Quart Stand Mixer',
    slug: 'kitchenaid-artisan-stand-mixer',
    price: 449,
    discountPrice: 379,
    stock: 20,
    category: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    brand: 'KitchenAid',
    images: ['https://images.unsplash.com/photo-1594385208974-2e75f8d7bb48?w=800'],
    description: '10-speed planetary mixing action with 5-quart bowl.',
    shortDescription: '325W motor, 5-quart bowl.',
    specifications: [{ key: 'Capacity', value: '5 Quarts' }],
    tags: ['mixer', 'kitchenaid'],
    rating: 4.9,
    numReviews: 210,
    isFeatured: true,
    salesCount: 480
  },
  {
    title: 'Philips XXL Digital Air Fryer 7.3L',
    slug: 'philips-xxl-digital-air-fryer',
    price: 299,
    discountPrice: 239,
    stock: 25,
    category: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    brand: 'Philips',
    images: ['https://images.unsplash.com/photo-1585515320310-259814833e62?w=800'],
    description: 'Rapid Air technology for 90% less fat cooking.',
    shortDescription: '7.3L capacity air fryer.',
    specifications: [{ key: 'Capacity', value: '7.3 Liters' }],
    tags: ['airfryer', 'philips'],
    rating: 4.8,
    numReviews: 175,
    isBestSeller: true,
    salesCount: 650
  },
  {
    title: 'Nespresso VertuoPlus Coffee Maker',
    slug: 'nespresso-vertuoplus-coffee-maker',
    price: 169,
    discountPrice: 129,
    stock: 30,
    category: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    brand: 'DeLonghi',
    images: ['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800'],
    description: 'Centrifusion extraction technology for barista espresso.',
    shortDescription: 'Includes milk frother.',
    specifications: [{ key: 'Technology', value: 'Centrifusion' }],
    tags: ['nespresso', 'coffee'],
    rating: 4.8,
    numReviews: 190,
    isFlashSale: true,
    salesCount: 520
  },
  {
    title: 'Instant Pot Duo 7-in-1 Pressure Cooker 6Qt',
    slug: 'instant-pot-duo-pressure-cooker',
    price: 99,
    discountPrice: 79,
    stock: 35,
    category: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    brand: 'Instant Pot',
    images: ['https://images.unsplash.com/photo-1544025162-d76694265947?w=800'],
    description: 'Replaces 7 appliances: pressure cooker, slow cooker, rice cooker.',
    shortDescription: '6-Quart stainless steel pot.',
    specifications: [{ key: 'Functions', value: '7 in 1' }],
    tags: ['instantpot', 'cooker'],
    rating: 4.8,
    numReviews: 310,
    salesCount: 980
  },
  {
    title: 'Cast Iron Enamelled Dutch Oven 5.5Qt',
    slug: 'cast-iron-dutch-oven-55qt',
    price: 180,
    discountPrice: 139,
    stock: 18,
    category: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    brand: 'Nexora Home',
    images: ['https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=800'],
    description: 'Heavyweight enamelled cast iron Dutch oven with self-basting spikes.',
    shortDescription: 'Oven safe up to 500°F.',
    specifications: [{ key: 'Material', value: 'Cast Iron' }],
    tags: ['dutchoven', 'cookware'],
    rating: 4.9,
    numReviews: 65,
    salesCount: 210
  },
  {
    title: 'Philips Smart HEPA Air Purifier',
    slug: 'vitashine-smart-hepa-air-purifier',
    price: 220,
    discountPrice: 175,
    stock: 22,
    category: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    brand: 'Philips',
    images: ['https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800'],
    description: '3-stage H13 True HEPA filter removes 99.97% of airborne dust.',
    shortDescription: 'Covers 500 sq ft room.',
    specifications: [{ key: 'Filter', value: 'H13 True HEPA' }],
    tags: ['airpurifier', 'philips'],
    rating: 4.8,
    numReviews: 82,
    salesCount: 310
  },
  {
    title: 'Damascus Steel 6-Piece Chef Knife Set',
    slug: 'japanese-steel-chef-knife-set',
    price: 195,
    discountPrice: 149,
    stock: 24,
    category: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    brand: 'Nexora Home',
    images: ['https://images.unsplash.com/photo-1593618998160-e34014e67546?w=800'],
    description: 'AUS-10 67-layer Damascus steel forged knives with pakkawood handles.',
    shortDescription: '67-Layer Damascus Steel.',
    specifications: [{ key: 'Steel', value: 'AUS-10 Damascus' }],
    tags: ['knives', 'chef'],
    rating: 4.9,
    numReviews: 54,
    isTopRated: true,
    salesCount: 180
  },
  {
    title: 'Smart Digital Countertop Convection Oven',
    slug: 'smart-digital-convection-oven',
    price: 250,
    discountPrice: 199,
    stock: 15,
    category: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    brand: 'DeLonghi',
    images: ['https://images.unsplash.com/photo-1585515320310-259814833e62?w=800'],
    description: '1800W convection countertop oven with 12 preset cooking functions.',
    shortDescription: '1800W Convection toaster oven.',
    specifications: [{ key: 'Power', value: '1800W' }],
    tags: ['oven', 'kitchen'],
    rating: 4.8,
    numReviews: 60,
    salesCount: 220
  },

  // FURNITURE (10)
  {
    title: 'Velvet Ergonomic Executive Chair',
    slug: 'velvet-ergonomic-executive-chair',
    price: 350,
    discountPrice: 285,
    stock: 15,
    category: 'furniture',
    categoryName: 'Furniture',
    brand: 'Nexora Living',
    images: ['https://images.unsplash.com/photo-1580481072645-022f9a6d8310?w=800'],
    description: 'Plum velvet upholstered desk chair with pneumatic tilt control.',
    shortDescription: '360° Swivel brass base.',
    specifications: [{ key: 'Material', value: 'Velvet & Brass' }],
    tags: ['chair', 'office'],
    rating: 4.8,
    numReviews: 42,
    isFeatured: true,
    isTrending: true,
    salesCount: 170
  },
  {
    title: 'Solid Walnut Wood Coffee Table',
    slug: 'solid-walnut-wood-coffee-table',
    price: 450,
    discountPrice: 390,
    stock: 8,
    category: 'furniture',
    categoryName: 'Furniture',
    brand: 'Nexora Living',
    images: ['https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=800'],
    description: 'Mid-century modern coffee table handcrafted from solid American black walnut.',
    shortDescription: '100% Solid Walnut.',
    specifications: [{ key: 'Wood', value: 'American Walnut' }],
    tags: ['table', 'walnut'],
    rating: 5.0,
    numReviews: 29,
    isTopRated: true,
    salesCount: 95
  },
  {
    title: 'Herman Miller Aeron Ergonomic Chair',
    slug: 'herman-miller-aeron-chair',
    price: 1450,
    discountPrice: 1290,
    stock: 10,
    category: 'furniture',
    categoryName: 'Furniture',
    brand: 'Herman Miller',
    images: ['https://images.unsplash.com/photo-1505797149-43b0069ec26b?w=800'],
    description: 'Pellicle suspension material with adjustable PostureFit SL lumbar support.',
    shortDescription: 'Fully adjustable ergonomic chair.',
    specifications: [{ key: 'Warranty', value: '12 Years' }],
    tags: ['hermanmiller', 'chair'],
    rating: 4.9,
    numReviews: 120,
    isFeatured: true,
    salesCount: 310
  },
  {
    title: 'West Elm Mid-Century 3-Seater Sofa',
    slug: 'mid-century-3-seater-sofa',
    price: 890,
    discountPrice: 750,
    stock: 6,
    category: 'furniture',
    categoryName: 'Furniture',
    brand: 'West Elm',
    images: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800'],
    description: 'Deep-seated sofa with high-density cushions and solid oak tapered legs.',
    shortDescription: 'Stain-resistant performance fabric.',
    specifications: [{ key: 'Seating', value: '3 Persons' }],
    tags: ['sofa', 'westelm'],
    rating: 4.8,
    numReviews: 45,
    salesCount: 120
  },
  {
    title: 'Industrial Iron & Wood Bookshelf 5-Tier',
    slug: 'industrial-iron-wood-bookshelf',
    price: 280,
    discountPrice: 225,
    stock: 14,
    category: 'furniture',
    categoryName: 'Furniture',
    brand: 'IKEA',
    images: ['https://images.unsplash.com/photo-1594620302200-9a762244a156?w=800'],
    description: 'Steel frame with reclaimed pine wood shelves.',
    shortDescription: '5-tier open shelving unit.',
    specifications: [{ key: 'Height', value: '180 cm' }],
    tags: ['bookshelf', 'ikea'],
    rating: 4.7,
    numReviews: 58,
    salesCount: 220
  },
  {
    title: 'Minimalist Arc Floor Lamp with Marble Base',
    slug: 'minimalist-arc-floor-lamp',
    price: 195,
    discountPrice: 155,
    stock: 20,
    category: 'furniture',
    categoryName: 'Furniture',
    brand: 'CB2',
    images: ['https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800'],
    description: 'Brushed brass arm with Carrara white marble base.',
    shortDescription: 'Brushed brass arc lamp.',
    specifications: [{ key: 'Height', value: '210 cm' }],
    tags: ['lamp', 'cb2'],
    rating: 4.8,
    numReviews: 38,
    salesCount: 140
  },
  {
    title: 'Solid Oak Dining Table 6-Seater',
    slug: 'solid-oak-dining-table-6seater',
    price: 780,
    discountPrice: 650,
    stock: 7,
    category: 'furniture',
    categoryName: 'Furniture',
    brand: 'Nexora Living',
    images: ['https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?w=800'],
    description: 'European white oak dining table with matte polyurethane finish.',
    shortDescription: 'Seats up to 6 adults.',
    specifications: [{ key: 'Length', value: '180 cm' }],
    tags: ['table', 'dining'],
    rating: 4.9,
    numReviews: 31,
    salesCount: 90
  },
  {
    title: 'Upholstered Queen Bed Frame with Storage',
    slug: 'upholstered-queen-bed-frame-storage',
    price: 650,
    discountPrice: 520,
    stock: 10,
    category: 'furniture',
    categoryName: 'Furniture',
    brand: 'West Elm',
    images: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800'],
    description: 'Tufted headboard with hydraulic lift-up underbed storage compartment.',
    shortDescription: 'Queen size with storage.',
    specifications: [{ key: 'Size', value: 'Queen' }],
    tags: ['bed', 'westelm'],
    rating: 4.8,
    numReviews: 50,
    salesCount: 160
  },
  {
    title: 'Modern Floating TV Stand Entertainment Unit',
    slug: 'modern-floating-tv-stand-unit',
    price: 320,
    discountPrice: 260,
    stock: 12,
    category: 'furniture',
    categoryName: 'Furniture',
    brand: 'IKEA',
    images: ['https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800'],
    description: 'Wall-mounted TV console with cable management routing and drop-down doors.',
    shortDescription: 'Fits up to 75" TVs.',
    specifications: [{ key: 'Width', value: '160 cm' }],
    tags: ['tvstand', 'ikea'],
    rating: 4.7,
    numReviews: 42,
    salesCount: 140
  },
  {
    title: 'Adjustable Electric Standing Desk 55x28"',
    slug: 'adjustable-electric-standing-desk',
    price: 499,
    discountPrice: 399,
    stock: 15,
    category: 'furniture',
    categoryName: 'Furniture',
    brand: 'Nexora Living',
    images: ['https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?w=800'],
    description: 'Dual-motor electric height adjustment from 28" to 48" with 4 memory presets.',
    shortDescription: 'Dual motor, 4 memory presets.',
    specifications: [{ key: 'Motor', value: 'Dual Motor' }],
    tags: ['standingdesk', 'office'],
    rating: 4.9,
    numReviews: 88,
    isBestSeller: true,
    salesCount: 380
  },

  // SPORTS (10)
  {
    title: 'Peloton Adjustable Dumbbell Set 5-52.5 lbs',
    slug: 'adjustable-dumbbell-set-5-52lbs',
    price: 420,
    discountPrice: 349,
    stock: 20,
    category: 'sports',
    categoryName: 'Sports',
    brand: 'Peloton',
    images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800'],
    description: 'Replaces 15 sets of dumbbells with turn dial mechanism from 5 to 52.5 lbs.',
    shortDescription: 'Quick select weight adjustment.',
    specifications: [{ key: 'Weight', value: '5 - 52.5 lbs' }],
    tags: ['fitness', 'peloton'],
    rating: 4.9,
    numReviews: 160,
    isBestSeller: true,
    isFlashSale: true,
    salesCount: 640
  },
  {
    title: 'Premium Non-Slip Rubber Yoga Mat 5mm',
    slug: 'premium-non-slip-rubber-yoga-mat',
    price: 78,
    discountPrice: 62,
    stock: 40,
    category: 'sports',
    categoryName: 'Sports',
    brand: 'Nexora Active',
    images: ['https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800'],
    description: '5mm thick eco-friendly tree rubber mat with laser etched alignment lines.',
    shortDescription: '5mm natural tree rubber.',
    specifications: [{ key: 'Thickness', value: '5mm' }],
    tags: ['yoga', 'mat'],
    rating: 4.8,
    numReviews: 84,
    salesCount: 380
  },
  {
    title: 'Under Armour HeatGear Compression Shirt',
    slug: 'under-armour-heatgear-compression-shirt',
    price: 45,
    discountPrice: 35,
    stock: 50,
    category: 'sports',
    categoryName: 'Sports',
    brand: 'Under Armour',
    images: ['https://images.unsplash.com/photo-1506152983158-b4a74a01c721?w=800'],
    description: 'Ultra-tight compression fit with moisture-wicking material.',
    shortDescription: 'UPF 30+ sun protection.',
    specifications: [{ key: 'Fit', value: 'Compression' }],
    tags: ['underarmour', 'gym'],
    rating: 4.7,
    numReviews: 110,
    salesCount: 490
  },
  {
    title: 'Salomon Speedcross 6 Trail Running Shoes',
    slug: 'salomon-speedcross-6-trail-shoes',
    price: 155,
    discountPrice: 129,
    stock: 25,
    category: 'sports',
    categoryName: 'Sports',
    brand: 'Salomon',
    images: ['https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=800'],
    description: 'Deep Mud Contagrip lugs for maximum traction on technical trails.',
    shortDescription: 'Quicklace system.',
    specifications: [{ key: 'Outsole', value: 'Mud Contagrip' }],
    tags: ['salomon', 'running'],
    rating: 4.9,
    numReviews: 95,
    isFeatured: true,
    salesCount: 320
  },
  {
    title: 'Wilson Pro Staff v14 Tennis Racket',
    slug: 'wilson-pro-staff-v14-racket',
    price: 279,
    discountPrice: 239,
    stock: 15,
    category: 'sports',
    categoryName: 'Sports',
    brand: 'Wilson',
    images: ['https://images.unsplash.com/photo-1617083934555-ac7d4fed8814?w=800'],
    description: 'Braid 45 construction provides precision control and feel.',
    shortDescription: '97 sq in head size.',
    specifications: [{ key: 'Head Size', value: '97 sq in' }],
    tags: ['wilson', 'tennis'],
    rating: 4.8,
    numReviews: 48,
    salesCount: 160
  },
  {
    title: 'Garmin Forerunner 265 Running Smartwatch',
    slug: 'garmin-forerunner-265-smartwatch',
    price: 449,
    discountPrice: 389,
    stock: 18,
    category: 'sports',
    categoryName: 'Sports',
    brand: 'Garmin',
    images: ['https://images.unsplash.com/photo-1510017803434-a899398421b3?w=800'],
    description: 'AMOLED touchscreen with morning report and multi-band GPS.',
    shortDescription: 'Up to 13 days battery life.',
    specifications: [{ key: 'Battery', value: '13 Days' }],
    tags: ['garmin', 'smartwatch'],
    rating: 4.9,
    numReviews: 130,
    isTopRated: true,
    salesCount: 410
  },
  {
    title: 'Resistance Loop Exercise Bands Set of 5',
    slug: 'resistance-loop-bands-set-of-5',
    price: 25,
    discountPrice: 18,
    stock: 65,
    category: 'sports',
    categoryName: 'Sports',
    brand: 'Nexora Active',
    images: ['https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=800'],
    description: 'Natural latex resistance bands ranging from X-Light to X-Heavy.',
    shortDescription: '5 resistance levels included.',
    specifications: [{ key: 'Material', value: 'Natural Latex' }],
    tags: ['bands', 'fitness'],
    rating: 4.8,
    numReviews: 220,
    isFlashSale: true,
    salesCount: 890
  },
  {
    title: 'Salomon Hydration Backpack 2L Water Bladder',
    slug: 'hydration-backpack-2l-bladder',
    price: 55,
    discountPrice: 42,
    stock: 30,
    category: 'sports',
    categoryName: 'Sports',
    brand: 'Salomon',
    images: ['https://images.unsplash.com/photo-1622260614153-03223fb72052?w=800'],
    description: 'Breathable mesh vest with leak-proof 2L reservoir.',
    shortDescription: '2L BPA-free reservoir.',
    specifications: [{ key: 'Capacity', value: '2 Liters' }],
    tags: ['backpack', 'salomon'],
    rating: 4.7,
    numReviews: 70,
    salesCount: 260
  },
  {
    title: 'Speedo Fastskin Competitive Swimming Goggles',
    slug: 'speedo-fastskin-swimming-goggles',
    price: 40,
    discountPrice: 32,
    stock: 45,
    category: 'sports',
    categoryName: 'Sports',
    brand: 'Speedo',
    images: ['https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800'],
    description: 'Anti-fog mirrored lenses with hydrodynamic profile.',
    shortDescription: 'Anti-fog mirrored lens.',
    specifications: [{ key: 'Lens', value: 'Mirrored Polycarbonate' }],
    tags: ['speedo', 'swimming'],
    rating: 4.8,
    numReviews: 65,
    salesCount: 210
  },
  {
    title: 'High-Density Foam Roller 18" Muscle Release',
    slug: 'high-density-foam-roller-18inch',
    price: 30,
    discountPrice: 22,
    stock: 55,
    category: 'sports',
    categoryName: 'Sports',
    brand: 'Nexora Active',
    images: ['https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800'],
    description: 'Molded EPP foam roller for deep tissue trigger point therapy.',
    shortDescription: '18-inch high density EPP foam.',
    specifications: [{ key: 'Material', value: 'EPP Foam' }],
    tags: ['foamroller', 'recovery'],
    rating: 4.8,
    numReviews: 120,
    salesCount: 450
  },

  // BOOKS (10)
  {
    title: 'The Art of Design & Architecture Hardcover',
    slug: 'the-art-of-design-and-architecture',
    price: 55,
    discountPrice: 42,
    stock: 30,
    category: 'books',
    categoryName: 'Books',
    brand: 'Penguin Classics',
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800'],
    description: 'Coffee table book documenting iconic modern architectural masterpieces.',
    shortDescription: '320 pages full color hardcover.',
    specifications: [{ key: 'Pages', value: '320' }],
    tags: ['book', 'design'],
    rating: 4.9,
    numReviews: 35,
    isTrending: true,
    salesCount: 150
  },
  {
    title: 'Atomic Habits by James Clear',
    slug: 'atomic-habits-james-clear',
    price: 27,
    discountPrice: 18,
    stock: 80,
    category: 'books',
    categoryName: 'Books',
    brand: 'Random House',
    images: ['https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=800'],
    description: 'An easy & proven way to build good habits and break bad ones.',
    shortDescription: 'Hardcover edition #1 NYT Bestseller.',
    specifications: [{ key: 'Author', value: 'James Clear' }],
    tags: ['book', 'bestseller'],
    rating: 5.0,
    numReviews: 650,
    isBestSeller: true,
    salesCount: 2100
  },
  {
    title: 'Designing Data-Intensive Applications',
    slug: 'designing-data-intensive-applications',
    price: 60,
    discountPrice: 48,
    stock: 40,
    category: 'books',
    categoryName: 'Books',
    brand: 'O\'Reilly',
    images: ['https://images.unsplash.com/photo-1532012197267-da84d127e765?w=800'],
    description: 'The definitive guide to distributed systems and storage engine architecture.',
    shortDescription: 'By Martin Kleppmann.',
    specifications: [{ key: 'Author', value: 'Martin Kleppmann' }],
    tags: ['tech', 'programming'],
    rating: 4.9,
    numReviews: 290,
    isTopRated: true,
    salesCount: 940
  },
  {
    title: 'Clean Code: Handbook of Software Craftsmanship',
    slug: 'clean-code-robert-martin',
    price: 50,
    discountPrice: 39,
    stock: 50,
    category: 'books',
    categoryName: 'Books',
    brand: 'Pearson',
    images: ['https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800'],
    description: 'Principles, patterns, and practices of writing clean maintainable code.',
    shortDescription: 'By Robert C. Martin.',
    specifications: [{ key: 'Author', value: 'Robert C. Martin' }],
    tags: ['programming', 'book'],
    rating: 4.8,
    numReviews: 380,
    salesCount: 1400
  },
  {
    title: 'Thinking, Fast and Slow by Daniel Kahneman',
    slug: 'thinking-fast-and-slow',
    price: 30,
    discountPrice: 22,
    stock: 60,
    category: 'books',
    categoryName: 'Books',
    brand: 'Farrar, Straus and Giroux',
    images: ['https://images.unsplash.com/photo-1495640388908-05fa85288e61?w=800'],
    description: 'Explores the two systems that drive the way we think: intuition vs deliberation.',
    shortDescription: 'Nobel laureate Daniel Kahneman.',
    specifications: [{ key: 'Pages', value: '512' }],
    tags: ['psychology', 'book'],
    rating: 4.8,
    numReviews: 420,
    salesCount: 1650
  },
  {
    title: 'Sapiens: A Brief History of Humankind',
    slug: 'sapiens-brief-history-humankind',
    price: 28,
    discountPrice: 20,
    stock: 70,
    category: 'books',
    categoryName: 'Books',
    brand: 'HarperCollins',
    images: ['https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=800'],
    description: 'Yuval Noah Harari spans the whole of human history from cognition to modernity.',
    shortDescription: 'By Yuval Noah Harari.',
    specifications: [{ key: 'Author', value: 'Yuval Noah Harari' }],
    tags: ['history', 'sapiens'],
    rating: 4.9,
    numReviews: 510,
    salesCount: 1890
  },
  {
    title: 'Leather Bound Hardcover Grid Journal 240p',
    slug: 'leather-bound-grid-journal',
    price: 24,
    discountPrice: 18,
    stock: 60,
    category: 'books',
    categoryName: 'Books',
    brand: 'Nexora Stationary',
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800'],
    description: '120gsm fountain pen friendly paper with ribbon bookmark.',
    shortDescription: 'A5 size 240 grid pages.',
    specifications: [{ key: 'Paper', value: '120gsm Acid-Free' }],
    tags: ['journal', 'stationary'],
    rating: 4.9,
    numReviews: 95,
    salesCount: 410
  },
  {
    title: 'The Psychology of Money by Morgan Housel',
    slug: 'psychology-of-money-morgan-housel',
    price: 25,
    discountPrice: 17,
    stock: 65,
    category: 'books',
    categoryName: 'Books',
    brand: 'Harriman House',
    images: ['https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=800'],
    description: 'Timeless lessons on wealth, greed, and happiness.',
    shortDescription: '19 short stories on financial behavior.',
    specifications: [{ key: 'Author', value: 'Morgan Housel' }],
    tags: ['finance', 'money'],
    rating: 4.9,
    numReviews: 310,
    isFeatured: true,
    salesCount: 1350
  },
  {
    title: 'Zero to One: Notes on Startups by Peter Thiel',
    slug: 'zero-to-one-peter-thiel',
    price: 26,
    discountPrice: 19,
    stock: 55,
    category: 'books',
    categoryName: 'Books',
    brand: 'Crown Business',
    images: ['https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=800'],
    description: 'How to build companies that create new things and progress.',
    shortDescription: 'By Peter Thiel.',
    specifications: [{ key: 'Author', value: 'Peter Thiel' }],
    tags: ['startups', 'business'],
    rating: 4.8,
    numReviews: 240,
    salesCount: 980
  },
  {
    title: 'The Pragmatic Programmer 20th Anniversary',
    slug: 'pragmatic-programmer-20th-edition',
    price: 52,
    discountPrice: 42,
    stock: 35,
    category: 'books',
    categoryName: 'Books',
    brand: 'Addison-Wesley',
    images: ['https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800'],
    description: 'From journeyman to master software development principles.',
    shortDescription: 'By David Thomas & Andrew Hunt.',
    specifications: [{ key: 'Edition', value: '20th Anniversary' }],
    tags: ['programming', 'book'],
    rating: 4.9,
    numReviews: 210,
    salesCount: 760
  },

  // GROCERY (10)
  {
    title: 'Organic Single-Origin Whole Coffee Beans 1kg',
    slug: 'organic-single-origin-coffee-beans-1kg',
    price: 34,
    discountPrice: 28,
    stock: 60,
    category: 'grocery',
    categoryName: 'Grocery',
    brand: 'Nexora Gourmet',
    images: ['https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800'],
    description: 'Medium roast Arabica coffee beans grown in Ethiopian high altitudes.',
    shortDescription: '100% Specialty Arabica 1kg.',
    specifications: [{ key: 'Weight', value: '1kg' }],
    tags: ['coffee', 'organic'],
    rating: 4.9,
    numReviews: 120,
    isBestSeller: true,
    salesCount: 780
  },
  {
    title: 'Cold-Pressed Extra Virgin Olive Oil 750ml',
    slug: 'cold-pressed-extra-virgin-olive-oil',
    price: 28,
    discountPrice: 22,
    stock: 50,
    category: 'grocery',
    categoryName: 'Grocery',
    brand: 'Nexora Gourmet',
    images: ['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800'],
    description: 'Single-estate early harvest EVOO from Koroneiki olives.',
    shortDescription: 'Acidity under 0.3%.',
    specifications: [{ key: 'Origin', value: 'Crete, Greece' }],
    tags: ['oliveoil', 'evoo'],
    rating: 4.9,
    numReviews: 88,
    salesCount: 390
  },
  {
    title: 'Raw Manuka Honey UMF 15+ MGO 514+',
    slug: 'raw-manuka-honey-umf15',
    price: 75,
    discountPrice: 59,
    stock: 30,
    category: 'grocery',
    categoryName: 'Grocery',
    brand: 'Whole Foods',
    images: ['https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800'],
    description: 'Pure authentic New Zealand Manuka honey UMF 15+ certified.',
    shortDescription: '250g jar UMF 15+.',
    specifications: [{ key: 'Grade', value: 'UMF 15+' }],
    tags: ['honey', 'superfood'],
    rating: 5.0,
    numReviews: 110,
    isFeatured: true,
    salesCount: 450
  },
  {
    title: 'Organic Japanese Ceremonial Matcha 100g',
    slug: 'japanese-ceremonial-matcha-100g',
    price: 45,
    discountPrice: 36,
    stock: 40,
    category: 'grocery',
    categoryName: 'Grocery',
    brand: 'Nexora Gourmet',
    images: ['https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=800'],
    description: 'Stone-ground Uji matcha powder with vibrant green color.',
    shortDescription: '100% Organic Uji Matcha.',
    specifications: [{ key: 'Origin', value: 'Kyoto, Japan' }],
    tags: ['matcha', 'tea'],
    rating: 4.9,
    numReviews: 95,
    isTopRated: true,
    salesCount: 380
  },
  {
    title: 'Artisanal Dark Chocolate 85% Cocoa 5-Pack',
    slug: 'artisanal-dark-chocolate-85-percent-5pack',
    price: 30,
    discountPrice: 24,
    stock: 45,
    category: 'grocery',
    categoryName: 'Grocery',
    brand: 'Whole Foods',
    images: ['https://images.unsplash.com/photo-1511381939415-e44015466834?w=800'],
    description: 'Bean-to-bar Ecuadorian dark chocolate bars sweetened with coconut sugar.',
    shortDescription: '5 x 80g bar pack.',
    specifications: [{ key: 'Cocoa', value: '85%' }],
    tags: ['chocolate', 'gourmet'],
    rating: 4.8,
    numReviews: 70,
    salesCount: 290
  },
  {
    title: 'Himalayan Pink Rock Salt Grinder 500g',
    slug: 'himalayan-pink-rock-salt-500g',
    price: 15,
    discountPrice: 11,
    stock: 80,
    category: 'grocery',
    categoryName: 'Grocery',
    brand: 'Organic Valley',
    images: ['https://images.unsplash.com/photo-1518110925495-5fe2f0e5a3c4?w=800'],
    description: 'Unrefined 100% natural mineral salt mined from Himalayas.',
    shortDescription: '500g refill grinder.',
    specifications: [{ key: 'Type', value: 'Unrefined Mineral Salt' }],
    tags: ['salt', 'himalayan'],
    rating: 4.8,
    numReviews: 130,
    salesCount: 650
  },
  {
    title: 'Aged Balsamic Vinegar of Modena 250ml',
    slug: 'aged-balsamic-vinegar-modena-250ml',
    price: 42,
    discountPrice: 32,
    stock: 25,
    category: 'grocery',
    categoryName: 'Grocery',
    brand: 'Nexora Gourmet',
    images: ['https://images.unsplash.com/photo-1508737804141-4c3b688e2546?w=800'],
    description: 'Traditional IGP Modena balsamic vinegar aged 12 years in wooden barrels.',
    shortDescription: 'Aged 12 years in casks.',
    specifications: [{ key: 'Aging', value: '12 Years' }],
    tags: ['balsamic', 'modena'],
    rating: 4.9,
    numReviews: 48,
    salesCount: 190
  },
  {
    title: 'Organic Roasted Almonds & Cashews 1kg',
    slug: 'organic-roasted-almonds-cashews-1kg',
    price: 32,
    discountPrice: 25,
    stock: 55,
    category: 'grocery',
    categoryName: 'Grocery',
    brand: 'Whole Foods',
    images: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800'],
    description: 'Dry roasted non-GMO organic almonds and cashews with sea salt.',
    shortDescription: '1kg resealable pouch.',
    specifications: [{ key: 'Weight', value: '1kg' }],
    tags: ['nuts', 'almonds'],
    rating: 4.8,
    numReviews: 140,
    isFlashSale: true,
    salesCount: 540
  },
  {
    title: 'Organic Grade-A Maple Syrup 500ml',
    slug: 'organic-grade-a-maple-syrup-500ml',
    price: 22,
    discountPrice: 17,
    stock: 50,
    category: 'grocery',
    categoryName: 'Grocery',
    brand: 'Organic Valley',
    images: ['https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800'],
    description: '100% pure Canadian dark amber maple syrup.',
    shortDescription: '500ml glass bottle.',
    specifications: [{ key: 'Origin', value: 'Quebec, Canada' }],
    tags: ['syrup', 'maple'],
    rating: 4.9,
    numReviews: 105,
    salesCount: 420
  },
  {
    title: 'Organic Whole Chia Seeds 1kg',
    slug: 'organic-whole-chia-seeds-1kg',
    price: 18,
    discountPrice: 14,
    stock: 65,
    category: 'grocery',
    categoryName: 'Grocery',
    brand: 'Organic Valley',
    images: ['https://images.unsplash.com/photo-1514733670139-4d87a1941d55?w=800'],
    description: 'High Omega-3 and fiber superfood chia seeds.',
    shortDescription: '1kg organic chia seeds.',
    specifications: [{ key: 'Weight', value: '1kg' }],
    tags: ['chiaseeds', 'superfood'],
    rating: 4.8,
    numReviews: 160,
    salesCount: 710
  },

  // ACCESSORIES (10)
  {
    title: 'Ray-Ban Polarized Aviator Sunglasses',
    slug: 'polarized-aviator-sunglasses',
    price: 165,
    discountPrice: 135,
    stock: 35,
    category: 'accessories',
    categoryName: 'Accessories',
    brand: 'Ray-Ban',
    images: ['https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800'],
    description: '100% UV protection G-15 polarized crystal lenses in classic gold wire frame.',
    shortDescription: 'Classic gold wire frame.',
    specifications: [{ key: 'Lens', value: 'Polarized G-15' }],
    tags: ['rayban', 'sunglasses'],
    rating: 4.8,
    numReviews: 92,
    isFeatured: true,
    isTrending: true,
    salesCount: 410
  },
  {
    title: 'Full-Grain Bifold RFID Leather Wallet',
    slug: 'full-grain-bifold-leather-wallet',
    price: 85,
    discountPrice: 68,
    stock: 45,
    category: 'accessories',
    categoryName: 'Accessories',
    brand: 'Nexora Leather',
    images: ['https://images.unsplash.com/photo-1627123424574-724758594e93?w=800'],
    description: 'Hand-stitched vegetable tanned leather wallet with built-in RFID shield.',
    shortDescription: 'RFID blocking 8 card slots.',
    specifications: [{ key: 'Material', value: 'Full-Grain Leather' }],
    tags: ['wallet', 'leather'],
    rating: 4.9,
    numReviews: 110,
    isBestSeller: true,
    salesCount: 520
  },
  {
    title: 'Waterproof Laptop Backpack 25L with USB',
    slug: 'waterproof-laptop-backpack-25l',
    price: 95,
    discountPrice: 75,
    stock: 40,
    category: 'accessories',
    categoryName: 'Accessories',
    brand: 'Samsonite',
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800'],
    description: '16-inch TSA laptop compartment with water-resistant Cordura nylon.',
    shortDescription: 'Fits 16" laptops with USB port.',
    specifications: [{ key: 'Capacity', value: '25 Liters' }],
    tags: ['backpack', 'samsonite'],
    rating: 4.8,
    numReviews: 135,
    salesCount: 480
  },
  {
    title: 'Fossil Minimalist Stainless Steel Chronograph',
    slug: 'fossil-minimalist-chronograph-watch',
    price: 159,
    discountPrice: 125,
    stock: 20,
    category: 'accessories',
    categoryName: 'Accessories',
    brand: 'Fossil',
    images: ['https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800'],
    description: '44mm quartz chronograph watch with blue dial and leather strap.',
    shortDescription: '50m water resistant watch.',
    specifications: [{ key: 'Case', value: '44mm Stainless Steel' }],
    tags: ['watch', 'fossil'],
    rating: 4.7,
    numReviews: 80,
    salesCount: 290
  },
  {
    title: 'Automatic Compact Windproof Umbrella',
    slug: 'automatic-windproof-compact-umbrella',
    price: 35,
    discountPrice: 26,
    stock: 60,
    category: 'accessories',
    categoryName: 'Accessories',
    brand: 'Nexora Accessories',
    images: ['https://images.unsplash.com/photo-1517479149777-5f3b6577d54c?w=800'],
    description: '9-rib fiberglass frame engineered to withstand wind gusts up to 55 mph.',
    shortDescription: 'Auto open/close 9-rib frame.',
    specifications: [{ key: 'Ribs', value: '9 Fiberglass Ribs' }],
    tags: ['umbrella', 'travel'],
    rating: 4.8,
    numReviews: 105,
    isFlashSale: true,
    salesCount: 440
  },
  {
    title: 'Unisex Cashmere Wool Winter Scarf',
    slug: 'unisex-cashmere-wool-winter-scarf',
    price: 65,
    discountPrice: 49,
    stock: 35,
    category: 'accessories',
    categoryName: 'Accessories',
    brand: 'Nexora Fashion',
    images: ['https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=800'],
    description: 'Fringed woven scarf crafted from 50% cashmere 50% wool.',
    shortDescription: '180 x 30 cm Cashmere blend.',
    specifications: [{ key: 'Dimensions', value: '180 x 30 cm' }],
    tags: ['scarf', 'winter'],
    rating: 4.9,
    numReviews: 62,
    salesCount: 210
  },
  {
    title: 'Polarized Wayfarer Matte Black Sunglasses',
    slug: 'wayfarer-matte-black-sunglasses',
    price: 150,
    discountPrice: 119,
    stock: 28,
    category: 'accessories',
    categoryName: 'Accessories',
    brand: 'Ray-Ban',
    images: ['https://images.unsplash.com/photo-1508296695146-257a814070b4?w=800'],
    description: 'Matte black acetate frame with anti-reflective polarized lenses.',
    shortDescription: 'Matte black frame with Green lenses.',
    specifications: [{ key: 'Frame', value: 'Acetate' }],
    tags: ['wayfarer', 'rayban'],
    rating: 4.8,
    numReviews: 140,
    salesCount: 520
  },
  {
    title: 'Genuine Leather Key Organizer Holder',
    slug: 'genuine-leather-key-organizer',
    price: 28,
    discountPrice: 20,
    stock: 50,
    category: 'accessories',
    categoryName: 'Accessories',
    brand: 'Nexora Leather',
    images: ['https://images.unsplash.com/photo-1614315517650-3771cf72d18a?w=800'],
    description: 'Compact key holder carrying up to 7 keys quietly.',
    shortDescription: 'Carries 2-7 keys compactly.',
    specifications: [{ key: 'Capacity', value: '7 Keys' }],
    tags: ['keychain', 'edc'],
    rating: 4.8,
    numReviews: 75,
    salesCount: 310
  },
  {
    title: 'Heavy-Duty Canvas Duffle Gym Bag 45L',
    slug: 'canvas-duffle-gym-bag-45l',
    price: 75,
    discountPrice: 58,
    stock: 30,
    category: 'accessories',
    categoryName: 'Accessories',
    brand: 'Samsonite',
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800'],
    description: '16oz heavy waxed canvas duffle bag with shoe compartment.',
    shortDescription: '45L weekender duffle.',
    specifications: [{ key: 'Volume', value: '45 Liters' }],
    tags: ['duffle', 'gymbag'],
    rating: 4.8,
    numReviews: 88,
    salesCount: 340
  },
  {
    title: 'Blue Light Blocking Computer Glasses',
    slug: 'blue-light-blocking-computer-glasses',
    price: 35,
    discountPrice: 25,
    stock: 65,
    category: 'accessories',
    categoryName: 'Accessories',
    brand: 'Nexora Accessories',
    images: ['https://images.unsplash.com/photo-1591076482161-42ce6da69f67?w=800'],
    description: 'Filters 99% of harmful digital blue light rays to reduce eye strain.',
    shortDescription: 'TR90 lightweight frame.',
    specifications: [{ key: 'Filter', value: '99% Blue Light' }],
    tags: ['glasses', 'bluelight'],
    rating: 4.8,
    numReviews: 160,
    isFlashSale: true,
    salesCount: 680
  }
];

const seedDB = async () => {
  try {
    const isConnected = await connectDB();
    if (!isConnected) {
      console.log('[NEXORA Seed] Database not connected. Skipping DB seed command.');
      return;
    }

    await User.deleteMany({});
    await Category.deleteMany({});
    await Product.deleteMany({});
    await Review.deleteMany({});
    await Order.deleteMany({});

    console.log('[NEXORA Seed] Existing collections cleared.');

    // Seed Admin & Users
    const adminUser = await User.create({
      name: 'NEXORA Admin',
      email: 'admin@nexora.com',
      password: 'admin123',
      role: 'admin',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
      phone: '+1 (800) 987-NEXORA'
    });

    const normalUser = await User.create({
      name: 'Eleanor Vance',
      email: 'user@nexora.com',
      password: 'user123',
      role: 'user',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=400',
      phone: '+1 (555) 123-4567',
      addresses: [
        {
          street: '740 Park Avenue, Apt 12B',
          city: 'New York',
          state: 'NY',
          zipCode: '10021',
          country: 'United States',
          isDefault: true
        }
      ]
    });

    console.log('[NEXORA Seed] Users seeded successfully.');

    // Seed Categories
    const createdCategories = await Category.insertMany(sampleCategories);
    console.log(`[NEXORA Seed] ${createdCategories.length} Categories seeded.`);

    // Seed 100 Products
    const createdProducts = await Product.insertMany(sampleProducts);
    console.log(`[NEXORA Seed] ${createdProducts.length} Products seeded.`);

    // Seed Sample Review
    await Review.create({
      user: normalUser._id,
      userName: normalUser.name,
      userAvatar: normalUser.avatar,
      product: createdProducts[0]._id,
      rating: 5,
      title: 'Phenomenal Sound & Noise Cancellation',
      comment: 'The Sony WH-1000XM5 headphones completely isolate ambient noise. Battery life is extraordinary.'
    });

    // Seed Sample Order
    await Order.create({
      orderNumber: 'NEX-982104',
      user: normalUser._id,
      orderItems: [
        {
          product: createdProducts[0]._id,
          title: createdProducts[0].title,
          price: createdProducts[0].discountPrice || createdProducts[0].price,
          image: createdProducts[0].images[0],
          quantity: 1
        }
      ],
      shippingAddress: normalUser.addresses[0],
      paymentMethod: 'Credit Card (Stripe)',
      itemsPrice: 349,
      taxPrice: 17.45,
      shippingPrice: 0,
      totalPrice: 366.45,
      isPaid: true,
      paidAt: Date.now(),
      status: 'Processing'
    });

    console.log('[NEXORA Seed] 100-product database seeding completed cleanly!');
    process.exit(0);
  } catch (error) {
    console.error(`[NEXORA Seed Error] ${error.message}`);
    process.exit(1);
  }
};

if (require.main === module) {
  seedDB();
}

module.exports = { seedDB, sampleProducts, sampleCategories };
